## classifiers
SVM, logistica, knn, tf

In [1]:
from modules.get_data import get_x_y

In [19]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [17]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [2]:
x,y = get_x_y()

/home/joaoholz/Documents/ufes/trabalho_final/modules/get_data.py:5: DtypeWarning: Columns (3,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv('asteroides/asteoides.csv').iloc[:,first_columns:]

In [44]:
def get_simple_metrics(x):
    desc = pd.DataFrame([x.min(),x.max(),x.mean(),x.median(),x.var(),x.kurtosis()]).transpose()
    desc.columns = ['min','max','mean','median','var','kurtosis']
    return desc

In [45]:
standard = StandardScaler()
standard.fit_transform(x)

In [46]:
get_simple_metrics(x)

                   min  ...   kurtosis
neo              0.000  ...     36.891
pha              0.000  ...    458.956
H               -1.100  ...      9.533
epoch      2425051.500  ...     67.676
epoch_mjd    25051.000  ...     67.676
epoch_cal 19270620.000  ...     67.662
e                0.000  ...      7.936
a           -14702.448  ... 550590.687
q                0.071  ...    268.332
i                0.008  ...     20.773
om               0.000  ...     -1.109
w                0.000  ...     -1.201
ma             -70.704  ...     -1.232
ad               0.654  ... 794871.813
n                0.000  ...     63.716
tp         2283183.406  ...    701.040
tp_cal    15390106.906  ...    693.693
per            151.192  ... 921885.845
per_y            0.000  ... 921888.730
moid             0.000  ...    264.646
moid_ld          0.000  ...    266.356
sigma_e          0.000  ...  64881.198
sigma_a          0.000  ... 425568.943
sigma_q          0.000  ...  61377.944
sigma_i          0.000  ...  85995.878
sigma_om         0.000  ... 700074.783
sigma_w          0.000  ... 926700.071
sigma_ma         0.000  ... 926702.084
sigma_ad         0.000  ... 464943.023
sigma_n          0.000  ... 443570.603
sigma_tp         0.000  ... 928338.727
sigma_per        0.000  ... 317999.359
rms              0.000  ... 955513.198

[33 rows x 6 columns]

In [47]:
pd.concat([
    pd.Series(x.columns),
    get_simple_metrics(pd.DataFrame(standard.fit_transform(x)))]         
,axis=1)

            0      min     max   mean  median   var   kurtosis
0         neo   -0.156   6.393  0.000  -0.156 1.000     36.891
1         pha   -0.046  21.516 -0.000  -0.046 1.000    458.956
2           H  -10.057   9.101  0.000  -0.004 1.000      9.533
3       epoch  -48.196   0.187 -0.000   0.187 1.000     67.676
4   epoch_mjd  -48.196   0.187  0.000   0.187 1.000     67.676
5   epoch_cal  -47.986   0.187 -0.000   0.187 1.000     67.662
6           e   -1.685  18.342 -0.000  -0.120 1.000      7.936
7           a -370.230 843.062  0.000  -0.006 1.000 550590.687
8           q   -1.087  36.463  0.000  -0.079 1.000    268.332
9           i   -1.363  25.013 -0.000  -0.247 1.000     20.773
10         om   -1.637   1.862  0.000  -0.084 1.000     -1.109
11          w   -1.746   1.719 -0.000   0.010 1.000     -1.201
12         ma   -2.344   2.970  0.000  -0.016 1.000     -1.232
13         ad   -0.039 933.119 -0.000  -0.006 1.000 794871.813
14          n   -2.980  27.002 -0.000  -0.098 1.000     63.716
15         tp -111.150  55.366  0.000   0.056 1.000    701.040
16     tp_cal -110.790  55.214  0.000   0.106 1.000    693.693
17        per   -0.002 969.465  0.000  -0.002 1.000 921885.845
18      per_y   -0.002 969.467 -0.000  -0.002 1.000 921888.730
19       moid   -0.656  36.194 -0.000  -0.081 1.000    264.646
20    moid_ld   -0.646  36.426  0.000  -0.074 1.000    266.356
21    sigma_e   -0.008 422.265  0.000  -0.008 1.000  64881.198
22    sigma_a   -0.004 737.911  0.000  -0.004 1.000 425568.943
23    sigma_q   -0.007 349.537 -0.000  -0.007 1.000  61377.944
24    sigma_i   -0.009 431.505 -0.000  -0.009 1.000  85995.878
25   sigma_om   -0.004 899.289  0.000  -0.004 1.000 700074.783
26    sigma_w   -0.001 965.727 -0.000  -0.001 1.000 926700.071
27   sigma_ma   -0.001 965.728  0.000  -0.001 1.000 926702.084
28   sigma_ad   -0.003 765.549  0.000  -0.003 1.000 464943.023
29    sigma_n   -0.005 784.390 -0.000  -0.005 1.000 443570.603
30   sigma_tp   -0.001 966.154  0.000  -0.001 1.000 928338.727
31  sigma_per   -0.003 690.359 -0.000  -0.003 1.000 317999.359
32        rms   -0.204 978.272 -0.000   0.002 1.000 955513.198